'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.18063
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("農地基本台帳.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property _112_DownArrowShort_Blue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_112_DownArrowShort_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;!DOCTYPE DataViewCongig [
        '''  &lt;!ELEMENT DataViewCongig (ControlGroups|DataViewNext)*&gt;
        '''  &lt;!ELEMENT ControlGroups (ControlGroup)*&gt;
        '''  &lt;!ELEMENT ControlGroup (DateTimePickerPlus|TextBoxPlus)*&gt;
        '''  &lt;!ELEMENT DataViewNext (FlowDirection?,CreateButton?,GroupBoxPlus+)&gt;
        '''  &lt;!ELEMENT FlowDirection (#PCDATA)&gt;
        '''  &lt;!ELEMENT CreateButton (#PCDATA)&gt;
        '''  &lt;!ELEMENT GroupBoxPlus (CustomControl|SetControlGroup|DateTimePickerPlus|TextBoxPlus|OptionButtonPlus|RichTextBoxNext|CheckButtonP [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property _Interface() As String
            Get
                Return ResourceManager.GetString("_Interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property cab() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cab", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property CLOSEFOLDERG() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOSEFOLDERG", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Collapse_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapse_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DataListViewカラム設定&gt;
        '''  &lt;xs:schema id=&quot;DataListViewカラム設定&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''    &lt;xs:element name=&quot;DataListViewカラム設定&quot; msdata:IsDataSet=&quot;true&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''      &lt;xs:complexType&gt;
        '''        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''          &lt;xs:element name=&quot;削除農地Columns&quot;&gt;
        '''            &lt;xs:complexType&gt;
        '''              &lt;xs:sequence&gt;
        '''                &lt;xs:element [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property DataListViewカラム設定() As String
            Get
                Return ResourceManager.GetString("DataListViewカラム設定", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xs:schema id=&quot;農地台帳&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;農地台帳&quot; msdata:IsDataSet=&quot;true&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;S_システム更新履歴&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;Key&quot; msdata:Caption=&quot;Key&quot; type=&quot;xs:string&quot; /&gt;
        '''           [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property DSet() As String
            Get
                Return ResourceManager.GetString("DSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property FARMER() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FARMER", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Folder_Back() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_Back", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Folder_stuffed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_stuffed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property help() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Human() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Human", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property

        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot; ?&gt;
        '''&lt;NewDataSet&gt;
        '''	&lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''		&lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;M_BASICALL&quot; msdata:Locale=&quot;ja-JP&quot;&gt;
        '''			&lt;xs:complexType&gt;
        '''				&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''					&lt;xs:element name=&quot;M_BASICALL&quot; msdata:CaseSensitive=&quot;False&quot; msdata:Locale=&quot;ja-JP&quot;&gt;
        '''						&lt;xs:complexType&gt;
        '''							&lt;xs:sequence&gt;
        '''								&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property M_BASICALL() As String
            Get
                Return ResourceManager.GetString("M_BASICALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Maintenance() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Maintenance", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Map() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Map", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Operation() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Operation", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Overlay_preferences() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Overlay_preferences", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property SearchItem() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SearchItem", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property SuccessComplete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuccessComplete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property UnCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 個人() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("個人", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 分筆処理() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("分筆処理", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 営農情報() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("営農情報", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;DataViewNext Name=&quot;土地履歴&quot;&gt;
        '''  &lt;GroupBoxPlus Name=&quot;管理情報&quot;&gt;
        '''    &lt;TextBoxPlus FieldName=&quot;ID&quot; ReadOnly=&quot;IsReadOnly&quot; WithLabel=&quot;ID&quot; /&gt;
        '''  &lt;/GroupBoxPlus&gt;
        '''&lt;/DataViewNext&gt; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property 土地履歴View() As String
            Get
                Return ResourceManager.GetString("土地履歴View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;SettingList xmlns=&quot;http://tempuri.org/PageLayout.xsd&quot;&gt;
        '''  &lt;PageConfig Name=&quot;基本画面&quot; CloseMode=&quot;CloseOK&quot;&gt;
        '''    &lt;QuadSplitContainer Name=&quot;QuadMain&quot; StartDistance=&quot;25%&quot; StartDistanceA=&quot;50%&quot; StartDistanceB=&quot;50%&quot;&gt;
        '''      &lt;Orientation value=&quot;#オリエンテーション&quot;/&gt;
        '''      &lt;PanelA&gt;
        '''        &lt;CanDragTabControl Name=&quot;TabA&quot; AllowDrop=&quot;true&quot; ImageSize=&quot;24&quot;&gt;
        '''          &lt;DropDownItems&gt;
        '''            &lt;ToolStripSeparator /&gt;
        '''            &lt;ToolStripMenuItem Name=&quot;転用農地検索2&quot; Text=&quot;転用農地検索&quot; Image=&quot;Se [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property 基本画面() As String
            Get
                Return ResourceManager.GetString("基本画面", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 履歴() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("履歴", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 法人() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("法人", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 生産法人() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("生産法人", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 田() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("田", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 申請() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("申請", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 畑() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("畑", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 農地() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("農地", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 農家世帯() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("農家世帯", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;Row ss:AutoFitHeight=&quot;0&quot;&gt;
        '''    &lt;Cell ss:StyleID=&quot;s26&quot;&gt;&lt;Data ss:Type=&quot;String&quot;&gt;{1}&lt;/Data&gt;&lt;NamedCell
        '''      ss:Name=&quot;Print_Area&quot;/&gt;&lt;/Cell&gt;
        '''    &lt;Cell ss:StyleID=&quot;s26&quot;&gt;&lt;Data ss:Type=&quot;String&quot;&gt;{2}&lt;/Data&gt;&lt;NamedCell
        '''      ss:Name=&quot;Print_Area&quot;/&gt;&lt;/Cell&gt;
        '''    &lt;Cell ss:StyleID=&quot;s27&quot;&gt;&lt;Data ss:Type=&quot;String&quot;&gt;{3}&lt;/Data&gt;&lt;NamedCell
        '''      ss:Name=&quot;Print_Area&quot;/&gt;&lt;/Cell&gt;
        '''    &lt;Cell ss:StyleID=&quot;s27&quot;&gt;&lt;Data ss:Type=&quot;String&quot;&gt;{4}&lt;/Data&gt;&lt;NamedCell
        '''      ss:Name=&quot;Print_Area&quot;/&gt;&lt;/Cell&gt;
        '''    &lt;Cell ss:StyleID=&quot;s27&quot;&gt;&lt;Data ss:Type=&quot;String [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend Shared ReadOnly Property 選挙リスト行() As String
            Get
                Return ResourceManager.GetString("選挙リスト行", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend Shared ReadOnly Property 選挙関連() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("選挙関連", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Class
End Namespace
